### ISSUE TITLE
Can I translate this book into Chinese?

### ISSUE THREAD

**Issue by Scrooge20291224** [farcaller/nbtb#10]
Look forward for your permission, thx!

**Comment by farcaller** [comment]
Sure, go ahead and thanks for asking. I'd appreciate if the text would be submitted as a pull request to this repo so that the gitbook's multilingual support would work.

**Comment by Scrooge20291224** [comment]
> Sure, go ahead and thanks for asking. I'd appreciate if the text would be submitted as a pull request to this repo so that the gitbook's multilingual support would work.

Ok, just do as you say. :-)
