### ISSUE TITLE
Typo in point of focus?

### ISSUE THREAD

**Issue by lucas-deangelis** [farcaller/nbtb#8]
First of all, I wanted to thank you for writing this book. It's a great resource, and the explanations are clear.

I think there may be a missing word in the chapter "Point of focus", in the second to last paragraph. The second to last sentence of this paragraph is "Let it develop own habits.", which I think is missing an "its" or "their", referring to "your tulpa" on the previous sentence.

I'm also not sure if you're still taking issues and pull requests, I wouldn't mind correcting the mistakes I find if I find any.

**Comment by farcaller** [comment]
A PR would be much appreciated, thanks.
